[project]
name = "dataframe-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "polars>=1.34.0",
    "rich>=14.2.0",
    "textual>=1.0.0",
]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]
